### ISSUE TITLE
[Design] Ресерч готовых вариантов макетов

### ISSUE THREAD

**Issue by Krimsit** [book-hub-umsp/book-hub-app#5]
Нужно найти в Figma Community несколько макетов, которые могут служить референсами для нашего дизайна

**Comment by Kawaii-Devil** [comment]
https://www.figma.com/team_invite/redeem/k4WWAGFu6XjdWSN8Rr6oaE
На мой взгляд наиболее подходящий проект это My book shelf, т к он больше остальных соответствует нашему т з
Остальные проекты Book Store Web App и SNAP, подойдут для рассмотрения отдельных элементов дизайна

**Comment by Krimsit** [comment]
3 найденных макета:

1. https://www.figma.com/design/Z5x6ugKtkdiPOcg1DD2Pvs/My-Book-Shelf-(Community)?node-id=1-2&node-type=canvas&t=lIDtlDTLORw5Aovu-0
2. https://www.figma.com/design/UuKSApHBB6bywwIMM0z6gu/SNAP%3A-A-Modern-and-Intuitive-Student-Non-Academic-Portal-Design-for-Collaborative-Learning-(Community)?node-id=0-1&node-type=canvas&t=SSuLQBIzGEbf7DLc-0
3. https://www.figma.com/design/HreRINWDhI9kbjSG08QBiy/Book-Store-Web-App-(Community)?node-id=0-1&node-type=canvas&t=SbB7KDErKnhQq4vg-0

**Comment by Krimsit** [comment]
Выбрали - https://www.figma.com/design/Z5x6ugKtkdiPOcg1DD2Pvs/My-Book-Shelf-(Community)?node-id=1-2&node-type=canvas&t=lIDtlDTLORw5Aovu-0
